name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get short SHA
        id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: x123rtyizzz/python-app:${{ steps.vars.outputs.sha_short }}
    outputs:
      commit_id: ${{ steps.vars.outputs.sha_short }}

  cd:
    needs: ci
    runs-on: self-hosted
    env:
      IMAGE_TAG: ${{ needs.ci.outputs.commit_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Argo CD CLI
        shell: bash
        run: |
          if command -v argocd >/dev/null 2>&1; then
            echo "argocd already installed: $(command -v argocd)"
            argocd version || true
            exit 0
          fi

          echo "Installing Argo CD CLI..."
          curl -sSL -o argocd \
            https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64

          chmod +x argocd

          if sudo mv argocd /usr/local/bin/argocd 2>/dev/null; then
            echo "Installed argocd to /usr/local/bin"
          else
            echo "No sudo or /usr/local/bin not writable, using local ./argocd"
            echo "$PWD" >> $GITHUB_PATH
            mv argocd ./argocd
          fi

      - name: Argo CD app set image & sync
        shell: bash
        run: |
          # Login to Argo CD
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username "${{ secrets.ARGOCD_USER }}" \
            --password "${{ secrets.ARGOCD_PASSWORD }}"

          echo "Deploying image tag: $IMAGE_TAG"

          # Override Helm value: image.tag=${IMAGE_TAG}
          argocd app set python-app \
            --helm-set image.tag=$IMAGE_TAG

          # Sync the application
          argocd app sync python-app
